---
abstract: 'Make skeleton code with Fey::ORM'
author:
  - 'Keedi Kim - 김도형 <keedi@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300000, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-mkfeyorm
requires:
  Data::Section: 0
  File::Basename: 0
  File::Spec::Functions: 0
  Getopt::Long::Descriptive: 0
  Moose: 0
  Moose::Util::TypeConstraints: 0
  MooseX::SemiAffordanceAccessor: 0
  MooseX::StrictConstructor: 0
  Template: 0
  autodie: 0
  strict: 0
  utf8: 0
  warnings: 0
resources:
  repository: http://github.com/keedi/App-mkfeyorm.git
version: 0.009
